version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: eduzone-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: eduzone-nitd
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin12345
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data:
    external: false
