import type { Metadata } from "next";
import { Inter, DM_Sans } from "next/font/google";
import "./globals.css";
import Navbar2 from "@/components/Navbar2";

const inter = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Eduzone NITD",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="dark">
            <body
                className={inter.className}
                style={{ position: "relative", overflowX: "hidden" }}
            >
                <Navbar2 />
                {children}
            </body>
        </html>
    );
}
