import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Eduzone NITD",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="dark">
            <body className={inter.className} style={{position: "relative", overflowX: "hidden"}}>
                <Navbar />
                    <div className="absolute bg-red-500 h-80 w-80 rounded-full left-1/3 top-1/3 mix-blend-exclusion -z-10 filter blur-xl opacity-70 animate-blob "></div>
                    <div className="absolute bg-cyan-500 h-80 w-80 rounded-full right-1/3 top-1/3 mix-blend-exclusion -z-10 filter blur-xl opacity-70 animate-blob animation-delay-2000"></div>
                    <div className="absolute bg-emerald-500 h-80 w-80 rounded-full left-[40%] top-1/2 mix-blend-exclusion -z-10 filter blur-xl opacity-70 animate-blob animation-delay-4000"></div>
                {children}
            </body>
        </html>
    );
}
